import { Timestamp } from 'firebase/firestore';
import { Category } from '../category/category.model';
import { Genre } from '../genre/genre.model';
import { Tag } from '../tag/tag.model';

export interface Episode {
  id?: string; // Episode ID, optional because it will be generated by Firestore
  createdAt: Timestamp;
  episodeDate: Timestamp;
  intelligence: string | null; // Inline markdown content
  isVisible: boolean;
  links: {
    spotify?: string;
    youtube?: string;
  };
  posterUrl: string | null;
  title: string;
}

export interface EpisodeWithRelations extends Episode {
  categories: Category[];
  genres: Genre[];
  tags: Tag[];
}
