import { FormControl } from '@angular/forms';
import { Timestamp } from 'firebase/firestore';
import { Category } from '../category/category.model';
import { Genre } from '../genre/genre.model';
import { Tag } from '../tag/tag.model';

export interface Episode {
  id?: string; // Episode ID, optional because it will be generated by Firestore
  createdAt: Timestamp;
  episodeDate: Timestamp;
  episodeDuration: number; // Duration in minutes
  intelligence: string | null; // Inline markdown content
  isVisible: boolean;
  links: {
    spotify?: string;
    youtube?: string;
  };
  posterUrl: string | null;
  title: string;
  year: number;
}

export interface EpisodeWithRelations extends Episode {
  categories: Category[];
  genres: Genre[];
  tags: Tag[];
}

export interface EpisodeForm {
  episodeDate: FormControl<Date>; // Using Date type for form control, will convert to Timestamp when saving
  episodeDuration: FormControl<number>;
  intelligence: FormControl<string | null>;
  isVisible: FormControl<boolean>;
  links: {
    spotify: FormControl<string | null>;
    youtube: FormControl<string | null>;
  };
  posterUrl: FormControl<string | null>;
  title: FormControl<string>;
  year: FormControl<number>;
}
