import { FormArray, FormControl, FormGroup } from '@angular/forms';
import { Timestamp } from 'firebase/firestore';
import { Category } from '../category/category.model';
import { Tag } from '../tag/tag.model';
import { Genre } from '../genre/genre.model';

export interface Episode {
  id?: string; // Episode ID, optional because it will be generated by Firestore
  about: string;
  createdAt: Timestamp;
  description: string;
  episodeDate: Timestamp;
  episodeDuration: number; // Duration in minutes
  isVisible: boolean;
  keyTakeaways: string[];
  links: {
    spotify?: string;
    youtube?: string;
  };
  quotes: string[];
  museum: MuseumItem[];
  thumbnailUrl: string | null;
  title: string;
  year: number;
}

export interface MuseumItem {
  name: string;
  explanation: string;
}

export interface EpisodeWithRelations extends Episode {
  categories: Category[];
  genres: Genre[];
  tags: Tag[];
}

export interface EpisodeForm {
  about: FormControl<string>;
  description: FormControl<string>;
  episodeDate: FormControl<Date>; // Using Date type for form control, will convert to Timestamp when saving
  episodeDuration: FormControl<number>;
  isVisible: FormControl<boolean>;
  keyTakeaways: FormArray<FormGroup<KeyTakeawayItemForm>>;
  links: {
    spotify: FormControl<string | null>;
    youtube: FormControl<string | null>;
  };
  quotes: FormArray<FormGroup<QuoteItemForm>>;
  museum: FormArray<FormGroup<MuseumItemForm>>;
  thumbnailUrl: FormControl<string | null>;
  title: FormControl<string>;
  year: FormControl<number>;
}

export interface KeyTakeawayItemForm {
  keyTakeaway: FormControl<string>;
}

export interface MuseumItemForm {
  name: FormControl<string>;
  explanation: FormControl<string>;
}

export interface QuoteItemForm {
  quote: FormControl<string>;
}
