import { FormControl } from '@angular/forms';
import { Episode } from '../episode/episode.model';

export interface Tag {
  id?: string; // Tag ID, optional because it will be generated by Firestore
  name: string;
  slug: string;
}

export interface TagWithRelations extends Tag {
  episodes: Episode[]; // Array of episodes associated with this tag
}

export interface TagForm {
  name: FormControl<string>;
  slug: FormControl<string>;
}
