import { FormControl } from '@angular/forms';
import { Episode } from '../episode/episode.model';

export interface Genre {
  id?: string; // Genre ID, optional because it will be generated by Firestore
  name: string;
  slug: string;
}

export interface GenreWithRelations extends Genre {
  episodes: Episode[];
}

export interface GenreForm {
  name: FormControl<string>;
  slug: FormControl<string>;
}
