import { Timestamp } from 'firebase/firestore';
import { Category } from '../category/category.model';
import { Genre } from '../genre/genre.model';
import { Tag } from '../tag/tag.model';

export interface Episode {
  id?: string; // Episode ID, optional because it will be generated by Firestore
  createdAt: Timestamp;
  episodeDate: Timestamp;
  intelligence: string | null; // Inline markdown content
  isVisible: boolean;
  links: {
    spotify?: string;
    youtube?: string;
  };
  title: string;
  // Denormalized taxonomy embedded directly on the episode document. Replaces the
  // former episodeCategories/episodeGenres/episodeTags junction collections.
  categories: Category[];
  genres: Genre[];
  tags: Tag[];
}

/**
 * Minimal episode shape for the archive list view (`/episodes`). The grid only
 * renders title + date, so the list loader projects to these three fields to keep
 * the unbounded taxonomy arrays out of the server-rendered transfer-state payload.
 */
export interface EpisodeListItem {
  id: string;
  title: string;
  episodeDate: Timestamp;
}
