import { FormControl } from '@angular/forms';
import { Episode } from '../episode/episode.model';

export interface Category {
  id?: string; // Category ID, optional because it will be generated by Firestore
  name: string;
  slug: string;
}

export interface CategoryWithRelations extends Category {
  episodes: Episode[]; // Array of episodes associated with this category
}

export interface CategoryForm {
  name: FormControl<string>;
  slug: FormControl<string>;
}
